[package]
name = "poever"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
everscale-types = { git = "https://github.com/broxus/everscale-types.git", branch = "hash-ref" }

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"